name: RISC-V ISA Build

on:
  push:
    branches:
      - main
      - dev_1
      - dev_2
      - dev_3
      - develop
  pull_request:
    branches:
      - main
      - dev_1
      - dev_2
      - dev_3
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Pull the latest RISC-V Docs container image
    # https://github.com/riscv/riscv-docs-base-container-image
    # https://hub.docker.com/r/riscvintl/riscv-docs-base-container-image
    - name: Pull Container
      id: pull_container_image
      run: |
        docker pull riscvintl/riscv-docs-base-container-image:latest

    # Build PDF and HTML files using the container
    - name: Build Files
      id: build_files
      if: steps.pull_container_image.outcome == 'success'
      run: |
        docker run --rm -v ${{ github.workspace }}:/build riscvintl/riscv-docs-base-container-image:latest \
        /bin/sh -c 'cd ./build && make'

    # Upload the unpriv-isa-asciidoc PDF file
    - name: Upload unpriv-isa-asciidoc.pdf
      if: steps.build_files.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: unpriv-isa-asciidoc.pdf
        path: ${{ github.workspace }}/build/unpriv-isa-asciidoc.pdf
        retention-days: 7
